// Servicios comunes en talleres mecánicos para autocompletar
export const SERVICIOS_COMUNES = [
  'Afinación mayor',
  'Afinación menor',
  'Cambio de aceite y filtro',
  'Cambio de anticongelante',
  'Cambio de balatas delanteras',
  'Cambio de balatas traseras',
  'Cambio de batería',
  'Cambio de bujías',
  'Cambio de líquido de frenos',
  'Cambio de pastillas de freno',
  'Cambio de terminal de dirección',
  'Diagnóstico computarizado',
  'Diagnóstico eléctrico',
  'Limpieza de inyectores',
  'Reparación de suspensión',
  'Revisión general',
  'Servicio de aire acondicionado',
  'Servicio de clutch',
  'Servicio de dirección',
  'Servicio de frenos',
  'Servicio de transmisión',
];

// Refacciones comunes
export const REFACCIONES_COMUNES = [
  'Aceite sintético',
  'Aceite semisintético',
  'Amortiguadores',
  'Anticongelante',
  'Balatas delanteras',
  'Balatas traseras',
  'Batería',
  'Bobina',
  'Bujías',
  'Cables de bujías',
  'Filtro de aceite',
  'Filtro de aire',
  'Filtro de combustible',
  'Líquido de frenos',
  'Pastillas de freno',
  'Terminal de dirección',
];

// Marcas de vehículos comunes en México
export const MARCAS_VEHICULOS = [
  'Acura',
  'Audi',
  'BMW',
  'Buick',
  'Cadillac',
  'Chevrolet',
  'Chrysler',
  'Dodge',
  'Fiat',
  'Ford',
  'GMC',
  'Honda',
  'Hyundai',
  'Infiniti',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Lincoln',
  'Mazda',
  'Mercedes-Benz',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Peugeot',
  'Porsche',
  'Ram',
  'Renault',
  'Seat',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];
